language: java
language: node_js
node_js:
 - 12


env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "unige-pinfo-2021" # the key of the org you chose at step #3
 
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules


jobs:
  include:
    - stage : Build
      script: 
      - ./travisScripts/buildtestK.sh
      - cd testIntegration
      - ./script.sh
      - cd ..
      - ./travisScripts/buildPushServices.sh
      - mvn sonar:sonar -Dsonar.projectKey=unige-pinfo-2021_PInfoGroupe5  -Dsonar.organization=unige-pinfo-2021 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1f5e5b54691d2c55908a51783053b2afef68ef5c
      
      after_success:
      - ./travisScripts/buildAfterSuccess.sh
      
