language: java
language: node_js
node_js:
 - 12


env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

addons:
  sonarcloud:
    organization: "khptif" # the key of the org you chose at step #3
 
cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules


jobs:
  include:
    - stage : Build
      script: 
      - ./travisScripts/buildtestK.sh
      - cd testIntegration
      - ./script.sh
      - cd ..
      - ./travisScripts/buildPushServices.sh
      - mvn sonar:sonar -Dsonar.projectKey=khptif_PInfoGroupe5  -Dsonar.organization=khptif -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=fd94ae81836ae6771bbd62e5fa1173f2a72770d4
      
      after_success:
      - ./travisScripts/buildAfterSuccess.sh
      
