language: java

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker



jobs:
  include:
    - stage : Build
      branch:
      	only:
      	 - master
      script:
      - ./travisScripts/buildPushServices.sh

