language: java
language: node_js
node_js:
 - 12

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules


jobs:
  include:
    - stage : Build
      script:
      - ./travisScripts/buildPushServices.sh

