language: java
language: node_js
node_js:
 - 12

env:
  - NODE_VERSION="12.13.1"
  
services:
  - docker

cache:
    directories:
      - .autoconf
      - $HOME/.m2
      - node_modules


jobs:
  include:
    - stage : Build
      script:
      - ./travisScripts/buildtestK.sh
      #- ./travisScripts/buildPushServices.sh
      - sudo apt-get install sshpass
      - sshpass -p ${serverPassword} ssh -q -o StrictHostKeyChecking=no ${server} cd serveurConfig && echo ${serverPassword} | sudo -S ./reset.sh
