apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: user
  template:
    metadata:
      labels:
        service: user
    spec:
      containers:
      - name: imageuser
        image: khptif/user:testintegration
        ports:
        - containerPort: 80
