apiVersion: batch/v1
kind: Job
metadata:
  name: test
spec:
  template:
    metadata:
      labels:
        test: integration
    spec:
      restartPolicy: OnFailure
      containers:
      - name: testIntegration
        image: testIntegration:latest
        ports:
        - containerPort: 8080
