apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: group
spec:
  replicas: 2
  selector:
    matchLabels:
      service: group
  template:
    metadata:
      labels:
        service: group
    spec:
      containers:
      - name: imagegroupe
        image: api/group:latest
        ports:
        - containerPort: 8080
